name: Commit to Notion CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: bb7hn/notionCommitter@main
        env: # Or as an environment variable
          SECRET_GITHUB  : ${{ secrets.SECRET_GITHUB }}
          NOTION_API_KEY  : ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE : ${{ secrets.NOTION_DATABASE }}
    #steps:
    #  - uses: actions/checkout@v3
    #  - name: Use Node.js ${{ matrix.node-version }}
    #    uses: actions/setup-node@v3
    #    with:
    #      node-version: ${{ matrix.node-version }}
    #      cache: 'npm'
    #  - run: npm ci --location=global
    #  - run: npm run build --if-present --location=global
    #  - run: npm test --location=global