name: Commit to Notion CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: cd/notion_committer/ 
      - run: ls
      #- run : node /notion_committer/index.js